FROM node:18-alpine as build-stage

WORKDIR /app

COPY package.json  pnpm-lock.yaml  ./

RUN npm install -g pnpm

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm run build

FROM nginx  as production-stage

# 复制编译后的前端代码
COPY --from=build-stage /app/dist  /usr/share/nginx/html
# 公开 Nginx 端口
EXPOSE 80
