FROM node:18-alpine as build-stage

WORKDIR /app

COPY package.json  pnpm-lock.yaml  ./

RUN npm install -g pnpm

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm run build

# 定义构建时变量
ARG VITE_ALCHEMY_KEY

# 设置环境变量（可选）
ENV VITE_ALCHEMY_KEY=${VITE_API_URL}

FROM nginx  as production-stage

# 复制编译后的前端代码
COPY --from=build-stage /app/dist  /usr/share/nginx/html
# 公开 Nginx 端口
EXPOSE 80
